galguerias/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('monoku/', include('monoku.urls', namespace="inventario")),
    path('admin/', admin.site.urls),
]

monoku/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'monoku'
urlpatterns = [
    path('', views.index, name='index'),
    path('Galguerias/', views.galgueria, name='galgueria'),
    path('personas/', views.personas, name='personas'),
    path('Preferecias_galguerias/', views.preferencias_galguerias, name='preferencias'),
    path('crear_personas/', views.crear_personas, name='crear_personas'),
    path('crear_galguerias/', views.crear_galguerias, name='crear_galguerias'),
    path('crear_preferencias/', views.crear_preferencias, name='crear_preferencias'),
    url(r'^login/$', views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^signup/$', views.signup, name='signup'),
    ]

monoku/models.py
from django.db import models


class Tipo_producto(models.Model):
    nombre = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre


class Galguerias(models.Model):
    nombre_producto = models.CharField(max_length=200)
    tipo = models.ForeignKey(Tipo_producto, on_delete=models.CASCADE)
    fecha_vencimiento = models.DateField()
    cantidad_producto = models.PositiveIntegerField(default=0)


    def __str__(self):
        return '{0} {1} {2}'.format(self.tipo, self.nombre_producto, self.cantidad_producto)


class Personas(models.Model):
    nombre_persona = models.CharField(max_length=200)
    edad = models.PositiveIntegerField(default=0)
    cargo = models.CharField(max_length=200)

    def __str__(self):
        return '{0}'.format(self.nombre_persona)


class Preferecias_galguerias(models.Model):
    persona = models.ForeignKey(Personas, on_delete=models.CASCADE)
    producto = models.ForeignKey(Galguerias, on_delete=models.CASCADE)
    cantidad_consumido = models.PositiveIntegerField(default=0)
    fecha = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{0} consumio {1} {2}'.format(self.persona.nombre_persona, self.cantidad_consumido,  self.producto.nombre_producto)

monoku/forms.py
from django import forms
from .models import Personas
from .models import Galguerias
from .models import Preferecias_galguerias
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class PersonaForm(forms.ModelForm):

    class Meta:
        model = Personas
        fields = ('nombre_persona', 'edad', 'cargo')
    def __init__(self,*args,**kwargs):
        super(PersonaForm,self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class':'form-control'

            })


class GalgueriaForm(forms.ModelForm):

    class Meta:
        model = Galguerias
        fields = ('nombre_producto', 'tipo', 'fecha_vencimiento', 'cantidad_producto')
    def __init__(self,*args,**kwargs):
        super(GalgueriaForm,self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class':'form-control'

            })


class PreferenciaForm(forms.ModelForm):

    class Meta:
        model = Preferecias_galguerias
        fields = ('persona', 'producto', 'cantidad_consumido')
    def __init__(self,*args,**kwargs):
        super(PreferenciaForm,self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class':'form-control'

            })


class UserCreationForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password')
    def __init__(self,*args,**kwargs):
        super(PreferenciaForm,self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class':'form-control'

            })


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    def __init__(self,*args,**kwargs):
        super(PreferenciaForm,self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class':'form-control'

            })
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

monoku/views.py
# Create your views here.
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from .models import Personas
from .models import Galguerias
from .models import Preferecias_galguerias
from .forms import PersonaForm
from .forms import GalgueriaForm
from .forms import PreferenciaForm
from .forms import SignUpForm
from django.shortcuts import redirect
from django.contrib.auth import login, authenticate


def index(request):
    latest_galguerias_list = Galguerias.objects.order_by('nombre_producto', 'tipo', 'cantidad_producto')
    context = {'latest_galguerias_list': latest_galguerias_list}
    return render(request, 'monoku/listar_galgerias.html', context)


def galgueria(request):
    galgueria = Galguerias.objects.all()
    #  context = {'galgueria': galgueria.values('nombre_producto')}
    return HttpResponse(galgueria.values('nombre_producto', 'tipo', 'cantidad_producto'))


def crear_galguerias(request):
    if request.method == "POST":
        form = GalgueriaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('http://127.0.0.1:8000/monoku/')
    else:
        form = GalgueriaForm()
    context = {
        'form': form
    }
    return render(request, 'monoku/crear_galguerias.html', context)


def personas(request):
    latest_personas_list = Personas.objects.order_by('nombre_persona', 'edad', 'cargo')
    template = loader.get_template('monoku/personas.html')
    context = {
        'latest_personas_list': latest_personas_list,
    }
    return HttpResponse(template.render(context, request))


def crear_personas(request):
    if request.method == "POST":
        form = PersonaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('monoku:personas')
    else:
        form = PersonaForm()
    context = {
        'form': form
    }
    return render(request, 'monoku/crear_personas.html', context)


def preferencias_galguerias(request):
    latest_preferencias_list = Preferecias_galguerias.objects.order_by('persona','producto', 'cantidad_consumido', 'fecha')
    template = loader.get_template('monoku/preferencias.html')
    context = {
        'latest_preferencias_list': latest_preferencias_list,
    }
    return HttpResponse(template.render(context, request))


def crear_preferencias(request):
    if request.method == "POST":
        form = PreferenciaForm(request.POST)
        if form.is_valid():
            print (form)
            cantidad = form['cantidad_consumido'].value()
            id_galgueria = form['producto'].value()
            seleccion = Galguerias.objects.get(pk=id_galgueria)
            consumo = seleccion.cantidad_producto - int(cantidad)
            seleccion.cantidad_producto = consumo
            seleccion.save()
            form.save()
            return redirect('http://127.0.0.1:8000/monoku/')
    else:
        form = PreferenciaForm()
    context = {
        'form': form
    }
    return render(request, 'monoku/crear_preferencias.html', context)


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            print (form)
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('http://127.0.0.1:8000/admin')
    else:
        form = SignUpForm()
    return render(request, 'monoku/signup.html', {'form': form})

monoku/templates/monoku/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Simple is Better Than Complex{% endblock %}</title>
  </head>
  <body>
    <header>
      <h1>My Site</h1>
      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">logout</a>
      {% else %}
        <a href="{% url 'login' %}">login</a> / <a href="{% url 'signup' %}">signup</a>
      {% endif %}
      <hr>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

monoku/templates/monoku/crear_galguerias.html
 {% extends 'monoku/index.html' %}

{% block content %}
  <div class="jumbotron">
        <h1 class="display-4">Crear Galguerias</h1>    
    </div>	
		<form action="{% url 'monoku:crear_galguerias' %}" method="post" >
    <div class="form-group">
      {% csrf_token %}
      {{ form.as_p}}
      
      <button type="submit" class="btn btn-primary">Crear</button>
    </div>
		</form>
{% endblock %}

monoku/templates/monoku/crear_personas.html
{% extends 'monoku/index.html' %}

{% block content %}
  <div class="jumbotron">
        <h1 class="display-4">Crear Persona</h1>    
    </div>	
		<form action="{% url 'monoku:crear_personas' %}" method="post">
				<div class="form-group">
			{% csrf_token %}
			{{ form.as_p}}
		</div>

			<!-- <input type="submit" value="Crear"> -->
			<button type="submit" class="btn btn-primary">Crear</button>
			</form>
{% endblock %}

monoku/templates/monoku/crear_preferencias.html
{% extends 'monoku/index.html' %}

{% block content %}
  <div class="jumbotron">
        <h1 class="display-4">Crear Preferencias</h1>    
    </div>	
		<form action="{% url 'monoku:crear_preferencias' %}" method="post">
		{% csrf_token %}
		{{ form.as_p}}

		<button type="submit" class="btn btn-primary">Crear</button>
		</form>
{% endblock %}

monoku/templates/monoku/home.html
{% extends 'base.html' %}

{% block content %}
  <h2>Welcome, {{ user.username }}!</h2>
{% endblock %}

monoku/templates/monoku/index.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
     <style>
        /* Sticky footer styles
        -------------------------------------------------- */
        html {
        position: relative;
        min-height: 100%;
        }
        body {
        /* Margin bottom by footer height */
        margin-bottom: 60px;
        }
        .footer {
        position: absolute;
        bottom: 0;
        width: 100%;
        /* Set the fixed height of the footer here */
        height: 60px;
        line-height: 60px; /* Vertically center the text there */
        background-color: #f5f5f5;
        }


        /* Custom page CSS
        -------------------------------------------------- */
        /* Not required for template or sticky footer method. */

        body > .container {
        padding: 60px 15px 0;
        }

        .footer > .container {
        padding-right: 15px;
        padding-left: 15px;
        }

        code {
        font-size: 80%;
        }
    </style>
    <title></title>
   
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <a class="navbar-brand" href="{% url 'inventario:index' %}">Galguerias</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
              
                <div class="collapse navbar-collapse" id="navbarsExampleDefault">

                   

                  <ul class="navbar-nav mr-auto">
                   <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Personas</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown01">
                            <a class="dropdown-item" href="{% url 'inventario:crear_personas' %}">Crear</a>
                            <a class="dropdown-item" href="{% url 'inventario:personas' %}">Listar</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Galguerias</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown01">
                            <a class="dropdown-item" href="{% url 'inventario:crear_galguerias' %}">Crear</a>
                            <a class="dropdown-item" href="{% url 'inventario:index' %}">Listar</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Preferencias</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown01">
                            <a class="dropdown-item" href="{% url 'inventario:crear_preferencias' %}">Crear</a>
                            <a class="dropdown-item" href="{% url 'inventario:preferencias' %}">Listar</a>
                        </div>
                    </li>
                   
                  </ul>
                  <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  </form>
                </div>
			  </nav>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

</body>
<footer class="footer">
      <div class="container">
        <span class="text-muted">Diplomado de python - 2019.</span>
      </div>
    </footer>
</html>

monoku/templates/monoku/listar_galgerias.html
 {% extends 'monoku/index.html' %}

{% block content %}
  <div class="jumbotron">
        <h1 class="display-4">Galguerias</h1>    
    </div>	
	{% if latest_galguerias_list %}
        <ul class="list-group">
        {% for galguerias in latest_galguerias_list %}
            <li class="list-group-item"><a href="/monoku/{{ galguerias.id }}/">{{ galguerias}}</a></li> 
        {% endfor %}
        </ul>
    {% else %}
        <div class="alert alert-primary" role="alert">
            <p>No galguerias are available.</p>
        </div>
    {% endif %}
{% endblock %}

 

monoku/templates/monoku/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>Log in to Galguerias</h2>
  {% if form.errors %}
    <p style="color: red">Your username and password didn't match. Please try again.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit">Log in</button>
    <a href="{% url 'signup' %}">New to Galguerias? Sign up</a>
  </form>
{% endblock %}

monoku/templates/monoku/personas.html
{% extends 'monoku/index.html' %}

{% block content %}
  <div class="jumbotron">
        <h1 class="display-4">Personas</h1>    
    </div>	
		{% if latest_personas_list %}
        <ul class="list-group">
        {% for personas in latest_personas_list %}
            <li class="list-group-item"><a href="/monoku/{{ personas.id }}/">{{ personas }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
    <div class="alert alert-primary" role="alert">
        <p>No monoku are available.</p>
    </div>
    {% endif %}
{% endblock %}

monoku/templates/monoku/preferencias.html
{% extends 'monoku/index.html' %}

{% block content %}
  <div class="jumbotron">
        <h1 class="display-4">Preferencias</h1>    
    </div>	
	{% if latest_preferencias_list %}
        <ul class="list-group">
        {% for preferencias in latest_preferencias_list %}
            <li class="list-group-item"><a href="/monoku/{{ preferencias.id }}/">{{ preferencias}}</a></li>
        {% endfor %}
        </ul>
    {% else %}
    <div class="alert alert-primary" role="alert">
        <p>No hay preferencias!.</p>
    </div>
    {% endif %}
{% endblock %}

monoku/templates/monoku/signup.html
{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}